### ISSUE TITLE
Consider reworking to avoid mutating prototype

### ISSUE THREAD

**Issue by wbhob** [safareli/default#1]
It's become a bit of an antipattern to manipulate the prototype, and transpilers like TypeScript don't support it at all. Would you be open to seeing a PR to change to a syntax such as the one below?

`default("bob", "tony") // bob`
`default(undefined, []) // []`

Thanks!

**Comment by safareli** [comment]
This is not maintained any more sorry

**Comment by wbhob** [comment]
would you be willing to release the package name? I'd be willing to maintain it for the forseeable future

**Comment by safareli** [comment]
If this lib becomes just a function then you can as well use
https://lodash.com/docs/4.17.10#defaults 
or
https://lodash.com/docs/4.17.10#defaultsDeep
which are already functions and would have better/faster implementation

I would recommend to use that instead of this.

**Comment by wbhob** [comment]
that is what I ended up doing. cheers!
